# Generated by Django 2.1 on 2018-08-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='make_report',
            new_name='report_url',
        ),
    ]
