# Generated by Django 2.1 on 2018-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=250)),
                ('org_logo', models.CharField(max_length=250)),
                ('what_converts', models.CharField(max_length=250)),
                ('presentation_id', models.CharField(max_length=250)),
                ('google_analytics', models.CharField(max_length=250)),
            ],
        ),
    ]
