# Generated by Django 2.1 on 2018-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
